# Generated by Django 3.1.3 on 2021-01-05 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField(max_length=10)),
                ('resume', models.FileField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='CareersOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=40)),
                ('isActive', models.BooleanField(default=True)),
                ('skills', models.TextField()),
                ('responsibilities', models.TextField()),
                ('createdOn', models.DateField(default=datetime.datetime(2021, 1, 5, 17, 43, 46, 593319, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=40)),
                ('inAdvisoryBoard', models.BooleanField(default=False)),
                ('in_C_Level', models.BooleanField(default=False)),
                ('createdOn', models.DateField(default=datetime.datetime(2021, 1, 5, 17, 43, 46, 676429, tzinfo=utc))),
            ],
        ),
    ]
