# Generated by Django 3.1.3 on 2021-01-05 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=phone_field.models.PhoneField(max_length=10),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 7, 55, 543921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 7, 55, 611020, tzinfo=utc)),
        ),
    ]
