# Generated by Django 3.1.3 on 2021-01-05 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0003_auto_20210106_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='IN'),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 56, 45, 38342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 56, 45, 120515, tzinfo=utc)),
        ),
    ]
