# Generated by Django 3.1.3 on 2021-01-05 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0006_auto_20210106_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 59, 47, 170748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 5, 18, 59, 47, 255258, tzinfo=utc)),
        ),
    ]
