# Generated by Django 3.1.3 on 2021-01-06 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0007_auto_20210106_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 20, 0, 487453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 20, 0, 454394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 20, 0, 487453, tzinfo=utc)),
        ),
    ]
