# Generated by Django 3.1.3 on 2021-01-06 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0008_auto_20210106_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 28, 51, 509946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 28, 51, 476582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 28, 51, 509946, tzinfo=utc)),
        ),
    ]
