# Generated by Django 3.1.3 on 2021-01-06 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tdb_project', '0009_auto_20210106_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='appliedOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 34, 13, 451925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careersopportunity',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 34, 13, 417706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teams',
            name='createdOn',
            field=models.DateField(default=datetime.datetime(2021, 1, 6, 6, 34, 13, 450927, tzinfo=utc)),
        ),
    ]
